#!/usr/bin/env python3
"""Calibrate the exact Bebop MJPEG stream for ORB-SLAM3's KannalaBrandt8 model."""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import cv2
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default="http://127.0.0.1:3000/video.mjpeg")
    parser.add_argument("--output", default="config/perception/bebop2.yaml")
    parser.add_argument("--board-cols", type=int, default=9, help="Inner chessboard corners across")
    parser.add_argument("--board-rows", type=int, default=6, help="Inner chessboard corners down")
    parser.add_argument("--square-size", type=float, default=0.024, help="Chessboard square size in meters")
    parser.add_argument("--samples", type=int, default=35)
    parser.add_argument("--sample-interval", type=float, default=0.45)
    parser.add_argument("--max-rms", type=float, default=1.5)
    parser.add_argument("--fps", type=int, default=30, help="Integer camera FPS required by ORB-SLAM3")
    return parser.parse_args()


def make_object_points(cols: int, rows: int, square_size: float) -> np.ndarray:
    points = np.zeros((1, cols * rows, 3), np.float64)
    grid = np.mgrid[0:cols, 0:rows].T.reshape(-1, 2)
    points[0, :, :2] = grid * square_size
    return points


def write_orb_settings(path: Path, width: int, height: int, fps: int, k: np.ndarray, d: np.ndarray, rms: float) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    values = {
        "fx": float(k[0, 0]),
        "fy": float(k[1, 1]),
        "cx": float(k[0, 2]),
        "cy": float(k[1, 2]),
        "k1": float(d[0, 0]),
        "k2": float(d[1, 0]),
        "k3": float(d[2, 0]),
        "k4": float(d[3, 0]),
    }
    path.write_text(
        f'''%YAML:1.0

# Generated by scripts/calibrate-bebop-camera.py
# Fisheye calibration RMS reprojection error: {rms:.6f} pixels
File.version: "1.0"
Camera.type: "KannalaBrandt8"
Camera1.fx: {values["fx"]:.12f}
Camera1.fy: {values["fy"]:.12f}
Camera1.cx: {values["cx"]:.12f}
Camera1.cy: {values["cy"]:.12f}
Camera1.k1: {values["k1"]:.12f}
Camera1.k2: {values["k2"]:.12f}
Camera1.k3: {values["k3"]:.12f}
Camera1.k4: {values["k4"]:.12f}
Camera.width: {width}
Camera.height: {height}
Camera.fps: {fps}
Camera.RGB: 0

ORBextractor.nFeatures: 1600
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 15
ORBextractor.minThFAST: 5

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
''',
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()
    board = (args.board_cols, args.board_rows)
    object_template = make_object_points(*board, args.square_size)
    object_points: list[np.ndarray] = []
    image_points: list[np.ndarray] = []

    source: int | str = int(args.source) if args.source.isdigit() else args.source
    capture = cv2.VideoCapture(source)
    capture.set(cv2.CAP_PROP_BUFFERSIZE, 1)
    if not capture.isOpened():
        print(f"Unable to open calibration source: {args.source}", file=sys.stderr)
        return 2

    image_size: tuple[int, int] | None = None
    last_sample = 0.0
    attempts = 0
    print(f"Collecting {args.samples} varied chessboard views from {args.source}")
    while len(image_points) < args.samples and attempts < args.samples * 80:
        ok, frame = capture.read()
        if not ok or frame is None:
            time.sleep(0.05)
            attempts += 1
            continue
        now = time.monotonic()
        if now - last_sample < args.sample_interval:
            continue
        last_sample = now
        attempts += 1
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        image_size = (gray.shape[1], gray.shape[0])
        found, corners = cv2.findChessboardCorners(
            gray,
            board,
            cv2.CALIB_CB_ADAPTIVE_THRESH | cv2.CALIB_CB_NORMALIZE_IMAGE | cv2.CALIB_CB_FAST_CHECK,
        )
        if not found:
            print(f"  no board ({len(image_points)}/{args.samples})")
            continue
        refined = cv2.cornerSubPix(
            gray,
            corners,
            (5, 5),
            (-1, -1),
            (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_MAX_ITER, 50, 1e-6),
        )
        object_points.append(object_template.copy())
        image_points.append(refined.reshape(1, -1, 2).astype(np.float64))
        print(f"  accepted {len(image_points)}/{args.samples}")

    capture.release()
    if image_size is None or len(image_points) < max(12, args.samples // 2):
        print("Not enough valid chessboard views. Use varied angles and cover the full image.", file=sys.stderr)
        return 3

    camera_matrix = np.zeros((3, 3), dtype=np.float64)
    distortion = np.zeros((4, 1), dtype=np.float64)
    rotation_vectors: list[np.ndarray] = []
    translation_vectors: list[np.ndarray] = []
    flags = (
        cv2.fisheye.CALIB_RECOMPUTE_EXTRINSIC
        | cv2.fisheye.CALIB_CHECK_COND
        | cv2.fisheye.CALIB_FIX_SKEW
    )
    rms, camera_matrix, distortion, rotation_vectors, translation_vectors = cv2.fisheye.calibrate(
        object_points,
        image_points,
        image_size,
        camera_matrix,
        distortion,
        rotation_vectors,
        translation_vectors,
        flags,
        (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_MAX_ITER, 100, 1e-7),
    )
    if not np.isfinite(camera_matrix).all() or not np.isfinite(distortion).all():
        print("Calibration produced non-finite parameters", file=sys.stderr)
        return 4
    if rms > args.max_rms:
        print(f"Calibration RMS {rms:.3f}px exceeds limit {args.max_rms:.3f}px", file=sys.stderr)
        return 5

    output = Path(args.output)
    write_orb_settings(output, image_size[0], image_size[1], args.fps, camera_matrix, distortion, rms)
    print(f"Wrote {output} with RMS {rms:.3f}px")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
